using System;
using System.Xml.Serialization;

namespace MongoSharp.Model
{
    [Serializable]
    public class MongoCollectionModelInfo
    {
        [XmlAttribute]
        public string RootClassName { get; set; }
        [XmlAttribute]
        public bool IsAutoGenerated { get; set; }
        [XmlAttribute]
        public int SampleSize { get; set; }
        [XmlAttribute]
        public decimal SamplePercent { get; set; }
        public string ModelCode { get; set; }

        [XmlIgnore]
        public MongoCollectionInfo Collection { get; set; }
    }  
}
